// <auto-generated />
using System;
using BoardGameRentalApp.Core.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BoardGameRentalApp.Core.Migrations
{
    [DbContext(typeof(BoardGameRentalDbContext))]
    [Migration("20220901191115_Third")]
    partial class Third
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("BoardGameRentalApp.Core.DTOs.BoardGameDTO", b =>
                {
                    b.Property<Guid>("BoardGameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("BoardGameId");

                    b.ToTable("listOfBoardGames");
                });

            modelBuilder.Entity("BoardGameRentalApp.Core.DTOs.UserDTO", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("listOfUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
